
[package]
authors = ["Nikolay Kost nk@artkost.dev"]
edition = "2021"
name    = "fast-staged"
publish = false
version = "0.1.0"

[dependencies]
fast_staged = { path = "../../crates/fast-staged" }
napi        = { version = "3", features = ["async"] }
napi-derive = "3.0.0"
tokio       = { version = "1.0", features = ["full"] }

[build-dependencies]
napi-build = "2"
