[build]
rustflags = ["-Zlocation-detail=none", "-Zfmt-debug=none"]

[target.release]
rustflags = ["-Zunstable-options", "-Cpanic=immediate-abort"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
